### ISSUE TITLE
请问有已发表论文吗

### ISSUE THREAD

**Issue by Lavender0225** [alibaba-research/ConceptGraph#1]
Very fancy work~

请问有已发表论文吗？希望有更系统、详细的方法说明，希望可以拜读一下，谢谢~

**Comment by zxlzr** [comment]
We have upload our KDD 2021 paper in https://arxiv.org/pdf/2106.01686.pdf

Demo is also available in http://openconcepts.openkg.cn/ (filtered dataset)
